### ISSUE TITLE
Installing from DevArch.vsix v0.1046, CustomProjectSystems folder, files not installed

### ISSUE THREAD

**Issue by jakenuts** [davidkron/DevArch#11]
Tried downloading the install from VS Gallery [here](https://visualstudiogallery.msdn.microsoft.com/82f1027c-a333-4a52-b712-b9fe066c9ba8). Created new DevArch project but got error when VS tried to load it and it's dependencies (CustomProject.Default.props) from the $(LocalAppData)\CustomProjectSystems\DevArchProject\ folder. This doesn't appear to have been created and files don't exist on disk. Is this extension dependent on another product?

**Comment by davidkron** [comment]
Thanks a lot for the feedback.
Apparently the DevArch project type can not be deployed through vsix because it requires to be put among local appdata. I have unpublished the extension from the VS gallery since this is such a major issue and will republish it again once I've found a better deployment solution. Probably by hosting the complete install of the extension through msi or create a nuget package for the project type and keep the VSIX.

**Comment by xmachine** [comment]
Hi David, I am facing same issue with my extension which has a project type included and same deployment issue exist ..i am not sure who copy this stuff at %LoacalAppData% , could you pls let me know how to fix it

**Comment by davjs** [comment]
Because my vsix package allready had an initialize function that was being run on vs startup i just copied the files over the first time the user started vs. There is most likely a better solution but thats what i did.
The function is here:
[ProjectDeployer.cs](https://github.com/davjs/DevArch/blob/d0d0e62fc4c4e2b32f9d0d67dcaec9a21ab230e1/Clients/VisualStudio/VsPackage/ProjectDeployer.cs)
And called from here:
[ToolsMenuPackage.cs](https://github.com/davjs/DevArch/blob/d0d0e62fc4c4e2b32f9d0d67dcaec9a21ab230e1/Clients/VisualStudio/VsPackage/ToolsMenuPackage.cs)

**Comment by xmachine** [comment]
Thanks , I followed sort of similar approach ...used msi installer to deploy these build files  , I will update thread if i find any recommended solution.
